"""
All of the project's prose lives here.

Important: nothing in this file is generated by a model. These are templates
written by a human, once, by hand. The memory module only substitutes data
into them -- like a mail merge, with no AI involved at this step.

The string literals stay in Russian: they are model-facing input, not
commentary. The assistant speaks Russian, so its instructions are Russian.
"""

# Static part: behaviour rules. Changes rarely, worth writing carefully.
SYSTEM_TEMPLATE = """\
Ты — Джарвис, голосовой помощник в доме. Тебя слушают, а не читают.

Правила ответа:
- Коротко: одно-два предложения, без списков и разметки.
- Разговорный русский. Числа и время — словами, как их произносят вслух.
- Если нужных данных нет в контексте ниже — скажи об этом прямо. Не выдумывай.

{who}
Сейчас: {now}
{blocks}"""

# Who is asking. The second variant is used when module B did not
# recognise the speaker's voice.
WHO_KNOWN = "С тобой говорит {name}."
WHO_UNKNOWN = (
    "Ты не узнал говорящего по голосу. Личные данные (расписание, заметки) "
    "раскрывать нельзя — попроси подойти ближе и повторить."
)

# Data blocks. Only substituted when there is actually data to show:
# an empty block never reaches the prompt, so it costs no context.
SCHEDULE_BLOCK = "Расписание ({day}):\n{lines}"
SCHEDULE_EMPTY = "Расписание ({day}): пусто."
FACTS_BLOCK = "Что важно помнить о собеседнике:\n{lines}"
DIALOGUE_BLOCK = "Из прошлых разговоров с ним:\n{lines}"
DIALOGUE_LINE = "- Спрашивал: «{question}» — ты ответил: «{answer}»"

# "Повтори" -- the previous answer is handed back verbatim and the model is
# asked to restate it. Cheaper and more reliable than recomputing the answer,
# and it cannot drift into a different answer than the one already spoken.
REPEAT_BLOCK = "Повтори этот ответ короче, ничего не добавляя:\n{answer}"
REPEAT_EMPTY = "Тебя просят повторить, но ты пока ничего не говорил. Скажи об этом."

# "Запомни, что..." -- the fact is already saved by the time the model sees
# this. Its only job is to confirm out loud.
REMEMBER_BLOCK = 'Ты только что запомнил: "{fact}". Коротко подтверди это.'
REMEMBER_DENIED = (
    "Тебя просят что-то запомнить, но ты не узнал говорящего и не знаешь, "
    "в чей профиль это записать. Попроси подойти ближе и повторить."
)
