"""
All of the project's prose lives here.

Important: nothing in this file is generated by a model. These are templates
written by a human, once, by hand. The memory module only substitutes data
into them -- like a mail merge, with no AI involved at this step.

The string literals stay in Russian: they are model-facing input, not
commentary. The assistant speaks Russian, so its instructions are Russian.
"""

# Static part: behaviour rules. Changes rarely, worth writing carefully.
SYSTEM_TEMPLATE = """\
Ты — Джарвис, голосовой помощник в доме. Тебя слушают, а не читают.

Правила ответа:
- Коротко: одно-два предложения, без списков и разметки.
- Разговорный русский. Все числа ниже уже написаны словами — так их и произноси, не переводи обратно в цифры.
- Если нужных данных нет в контексте ниже — скажи об этом прямо. Не выдумывай.
В твоём ответе должны быть только буквы и знаки препинания. Никаких чисел, никаких специальных символов. Всё прописывай словами.
{who}
Сейчас: {now}
{blocks}"""

# Who is asking. The second variant is used when module B did not
# recognise the speaker's voice.
WHO_KNOWN = "С тобой говорит {name}."
WHO_KNOWN_AGE = "С тобой говорит {name}. Возраст: {age}."
WHO_UNKNOWN = (
    "Ты не узнал говорящего по голосу. Личные данные (расписание, заметки) "
    "раскрывать нельзя — попроси подойти ближе и повторить."
)
# Same situation, but the question is not personal -- weather, places,
# small talk. Refusing would be absurd; answer as you would a guest.
WHO_GUEST = "Говорящий не опознан. Отвечай как гостю, ничьих личных данных не упоминай."

# Data blocks. Only substituted when there is actually data to show:
# an empty block never reaches the prompt, so it costs no context.
SCHEDULE_BLOCK = "Расписание ({day}):\n{lines}"
SCHEDULE_EMPTY = "Расписание ({day}): пусто."
FACTS_BLOCK = "Что важно помнить о собеседнике:\n{lines}"
DIALOGUE_BLOCK = "Из прошлых разговоров с ним:\n{lines}"
DIALOGUE_LINE = "- Спрашивал: «{question}» — ты ответил: «{answer}»"

# "Повтори" -- the previous answer is handed back verbatim and the model is
# asked to restate it. Cheaper and more reliable than recomputing the answer,
# and it cannot drift into a different answer than the one already spoken.
REPEAT_BLOCK = "Повтори этот ответ короче, ничего не добавляя:\n{answer}"
REPEAT_EMPTY = "Тебя просят повторить, но ты пока ничего не говорил. Скажи об этом."

# "Запомни, что..." -- the fact is already saved by the time the model sees
# this. Its only job is to confirm out loud.
REMEMBER_BLOCK = 'Ты только что запомнил: "{fact}". Коротко подтверди это.'
# A dislike is worth confirming differently: what changed is not that
# something was written down, it is that the assistant will now behave
# differently, and saying so is how the person finds out it worked.
REMEMBER_DISLIKE_BLOCK = ('Ты запомнил, что «{subject}» предлагать не нужно. '
                          'Коротко подтверди, что больше не будешь.')

# --- live data: weather (weatherapi.com) and places (2GIS) ------------------
# Every failure mode has its own sentence, so the model says what actually
# happened instead of inventing a forecast.
WEATHER_NO_KEY = ("Погода: сервис не настроен, ключа API нет. "
                  "Скажи, что пока не можешь узнать погоду.")
WEATHER_UNAVAILABLE = "Погода: сервис сейчас не отвечает. Скажи об этом честно."
WEATHER_STALE = "(Сервис не ответил — это последние известные данные, они могли устареть.)"
WEATHER_PAST = "Погода за прошедшие дни недоступна. Скажи об этом."
WEATHER_TOO_FAR = "Прогноза на {day} пока нет, есть только на три дня вперёд."

PLACES_NO_KEY = ("Поиск мест: сервис не настроен, ключа 2GIS нет. "
                 "Скажи, что пока не можешь искать места.")
PLACES_NO_QUERY = ("Тебя спрашивают о местах поблизости, но непонятно, что "
                   "именно искать. Переспроси.")
PLACES_UNAVAILABLE = "Поиск мест по запросу «{query}»: сервис не отвечает. Скажи об этом честно."
PLACES_NONE = "Поиск мест по запросу «{query}»: поблизости ничего не нашлось."
PLACES_BLOCK = "Места поблизости по запросу «{query}» (расстояние от дома):\n{lines}"
PLACES_STALE = "(Данные из кэша, могли устареть.)"

# --- one shape of answer per shape of question ------------------------------
# These replace the old "here are four businesses with four fields each"
# block. Each names exactly one place and carries only the fields that answer
# the question asked, because a field the answer does not need is a field the
# model can attach to the wrong name -- which is precisely what happened:
# "Аптека Экона, Морской проспект, шесть, восемьсот семьдесят метров" took its
# name, address and distance from three different listings.
#
# The register is the same as REMEMBER_BLOCK above: the code states the
# finished fact, the model's whole job is to say it in a sentence. Nothing
# below asks it to compare, filter or choose -- places.py has already done
# that. Phrasings avoid adjectives that would have to agree in gender with
# the business name ("открыт" / "открыта"), since the model copies whatever
# it is shown and the name is not known in advance.
PLACE_NEAREST_BLOCK = ('Самое близкое место — «{name}», до него {distance}. '
                       'Скажи об этом одним предложением.')
PLACE_OPEN_NOW_BLOCK = ('Сейчас работает «{name}», {address}. Скажи об этом '
                        'одним предложением.')
PLACE_NONE_OPEN_BLOCK = ('Сейчас поблизости не работает ничего. Раньше всех '
                         'откроется «{name}» — {opens}. Скажи об этом.')
PLACE_NONE_OPEN_UNKNOWN = ('Сейчас поблизости не работает ничего, и когда '
                           'откроется — неизвестно. Скажи об этом.')
PLACE_OPENS_EARLIEST_BLOCK = ('Раньше всех откроется «{name}» — {opens}. '
                              'Скажи об этом одним предложением.')
PLACE_ALWAYS_OPEN_BLOCK = ('«{name}» работает круглосуточно. Скажи об этом '
                           'одним предложением.')
PLACE_HOURS_BLOCK = ('«{name}» сегодня работает {hours}. Скажи об этом одним '
                     'предложением.')
PLACE_ADDRESS_BLOCK = ('«{name}» находится по адресу: {address}. Скажи об этом '
                       'одним предложением.')
PLACE_RATING_BLOCK = ('Лучшее по отзывам место — «{name}», рейтинг {rating}, '
                      '{reviews}. Скажи об этом одним предложением.')
PLACE_LIST_BLOCK = ('Поблизости есть: {names}. Перечисли их, больше ничего не '
                    'добавляй.')

# A distance question refers to a place named in the previous turn. Answered
# from memory, without a new search: searching again could quietly answer
# about a different business than the one the question meant.
PLACE_DISTANCE_BLOCK = ('До места «{name}» — {distance}. Скажи об этом одним '
                        'предложением.')
PLACE_DISTANCE_UNKNOWN = ('Тебя спрашивают, далеко ли это, но ты пока не '
                          'называл никакого места. Переспроси, о чём речь.')

# Missing fields get their own sentence rather than an empty slot: a template
# with a hole in it is answered with an invention.
PLACE_NO_HOURS = 'Часы работы места «{name}» неизвестны. Скажи об этом.'
PLACE_NO_ADDRESS = 'Адрес места «{name}» неизвестен. Скажи об этом.'
# --- music (Spotify) --------------------------------------------------------
# By the time the model sees any of these the command has already run, exactly
# as with REMEMBER above. Its job is to confirm, not to decide -- so none of
# them offers it a choice, and the failures each say what actually happened
# rather than leaving it to guess.
MUSIC_PLAYING = 'Ты включил «{name}». Коротко подтверди это.'
MUSIC_RESUMED = 'Ты продолжил воспроизведение. Коротко подтверди это.'
MUSIC_PAUSED = 'Ты поставил музыку на паузу. Коротко подтверди это.'
MUSIC_NEXT_BLOCK = 'Ты переключил на следующий трек. Коротко подтверди это.'
MUSIC_PREVIOUS_BLOCK = 'Ты вернулся к предыдущему треку. Коротко подтверди это.'

MUSIC_LOUDER_BLOCK = 'Ты сделал громче. Коротко подтверди это.'
MUSIC_QUIETER_BLOCK = 'Ты сделал тише. Коротко подтверди это.'
MUSIC_VOLUME_UNSUPPORTED = ('Громкостью этого устройства управлять нельзя. '
                            'Скажи, что её придётся поменять вручную.')
MUSIC_NOW_PLAYING = 'Сейчас играет «{name}». Скажи об этом одним предложением.'
MUSIC_NOTHING_PLAYING = 'Сейчас ничего не играет. Скажи об этом.'

MUSIC_NO_KEY = ('Музыка: сервис не настроен, доступа к Spotify нет. '
                'Скажи, что пока не можешь включать музыку.')
MUSIC_NOT_FOUND = 'Ничего похожего на «{query}» найти не удалось. Скажи об этом.'
# The one that actually happens: Spotify refuses to start playback unless the
# app is already open somewhere. Worth its own sentence, because "сервис не
# отвечает" would point at the wrong problem entirely.
MUSIC_NO_DEVICE = ('Spotify не открыт ни на одном устройстве, поэтому включить '
                   'музыку не получилось. Попроси открыть приложение.')
MUSIC_UNAVAILABLE = 'Управлять музыкой сейчас не получается. Скажи об этом честно.'

PLACE_NO_RATING = ('Оценок и отзывов нет. Ближайшее подходящее место — '
                   '«{name}». Скажи об этом.')
